### ISSUE TITLE
Some assistance please

### ISSUE THREAD

**Issue by Schnoopie-Doopie** [blacktirion/email-oauth2-proxy-docker#19]
Good monring all,

Perhaps im just being dumb but I can for the life of me get this to work in docker.

I have setup the Azure app and tested the config running on a windows install however I cant get it to work in Docker with the same config. First I thought just coping the config with the token details would work but it tell me " Retrying login due to exception while decrypting OAuth 2.0 credentials for my@email.address (invalid password): InvalidToken()"

Trying to run the docker container again then telnet into on port 1993 and issue command a1 login my@email.address password produces a url link in the logs however when I open it, i pass the Azure login and am redirected to http://localhost as configured in the Azure app. As this is started from my PC and not the dcoker container, it doesnt work. I've tried replaceing the localhost with the containers IP but still no joy. 

The log eventually report a timeout waiting for auth.

Any assistance would be great

**Comment by blacktirion** [comment]
I can't tell without a config dump (if you do end up uploading your config, make sure to sanitize it). But it sounds like you copied the same config from the windows box to the docker? If so, this probably won't work. The oauth proxy is made to re-encrypt the secrets and soforth to make sure that no one can read them after the fact. 

If this is what you did, you'll need to use the same config, but paste the token/secrets from scratch so that they are re-encrypted by the docker version.

**Comment by Schnoopie-Doopie** [comment]
[Redacted.log](https://github.com/blacktirion/email-oauth2-proxy-docker/files/13453728/Redacted.log)
[Redacted.config.txt](https://github.com/blacktirion/email-oauth2-proxy-docker/files/13453735/Redacted.config.txt)

HI Blacktirion,

Thanks for your quick response. 

Yes I did attempt to copy the config including the cert details from a windows pc but didnt work. I removed this and tried again.

To me, and i am no expert, the MS login works, asks for my email address and password, and then rediects to the URL listed in the Azure app (http://localhost) however, with no access to abrowser from within the docker container, localhost tries to open this on the windows PC being used. If I change the returned URI to the IP of the docker container (10.1.1.65) I still get a 404 error. 

I guess where im getting confussed is how do I open the localhost web page from outside of the container. 

I have attached my docker compose file for reference.

[Docker-Compose.txt](https://github.com/blacktirion/email-oauth2-proxy-docker/files/13453747/Docker-Compose.txt)

**Comment by blacktirion** [comment]
Hello @Schnoopie-Doopie,

Since I am not the maintainer on this proxy, I would have to defer to the main repo for this behavior, as it does not make sense to me, but I do not use it in this manner.

While I do use it for exchange online, I approach it with another method:

https://github.com/lakelse/videos/tree/master/04-install-email-oauth2-proxy-youtube

This on this Github are the instructions I followed to get Exchange Online to work. And while I have no doubt that the method laid out in the configuration works, I am unable to vouch for if it in regards to my experience. 

The above method will bypass the need for a redirect URI or callback URL. It allows more of a centralized approach to management instead of having to log in. If this does not suit your needs, I might be able to assist further, since I play around in Azure quite a bit.

Regarding the behavior of the call-back URL: I assume you are pasting this URL (from the log output) into your Windows Browser. The attempt back to the docker container should be over the same browser. I know you say you're getting a 404, but that should be resolving to a valid page, since it appears to be listening. Seeing a 404 is at least a good sign that you can reach the container on (what I assume) is port 80. I just am not sure if the entire callback path is in the config, or in the examples of the config.

Additionally, I just saw this snippet in the config:

> In addition, if you are using this proxy option in a setup that
> 	is not directly exposed (such as a container or private network) you may also need to map `redirect_uri` traffic via
> 	a private address. Once this is configured (via external tools/rules), instruct the proxy to listen here using the
> 	parameter `redirect_listen_address` - for example, `redirect_listen_address = http://10.0.0.0:8080`.

I'm not entirely sure what that means, but maybe that is what you need to look at? May require both redirect_uri and redirect_listen_address. Though I don't know if it's expecting the Network Address of the container (shouldn't apply in your case) or the actual host address.

Lastly, I would recommend removing anything from your config that does not explicitly pertain to your setup, just to tidy things up and if others have to get involved, it will make it easier to read. 

Let me know if this helps. 

Thanks.

**Comment by blacktirion** [comment]
@Schnoopie-Doopie has any of the above helped? I wanted to make sure I'm not leaving this issue open if so.

**Comment by moriahmorgan** [comment]
Closing due to no response
